### ISSUE TITLE
Hardware costs question

### ISSUE THREAD

**Issue by corpetty** [cyber-drop/ethereum_analytical_db#1]
Hey yall, 

Can all of this be implemented on a single machine, or did you break it up like you do in the requirements section?  

Trying to price out implementation of this.

Single instance (a bit below your tested hardware) goes to about a minimum of about 160 USD/month.
Separate hosts probably about 200 USD/month.

Sound about right?

**Comment by Snedashkovsky** [comment]
The solution works fine on a single machine.  
We use this server:  
- CPU: 6 cores (12 threads), 3.50 GHz
- RAM: 252 GB
- Space: 1 TB SSD

**Comment by corpetty** [comment]
Thanks for letting us know.  As an aside, do you guys allow access to this in any way?

**Comment by Snedashkovsky** [comment]
We can provide access to our database, the preliminary cost will be from $500/mo, depending on the load.
We are also ready to adapt the solution to your needs - create a issue, discuss it.
